DEBUG 2016-06-30 17:59:38,083: 	 Executing command: 'status'
DEBUG 2016-06-30 17:59:38,083: 	 Found CRAB cache file /afs/cern.ch/user/j/junho/.crab3
ERROR 2016-06-30 17:59:38,084: 	 Error: crab_ST_tw is not a valid CRAB project directory.
ERROR 2016-06-30 17:59:38,084: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 254, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 749, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 563, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_ST_tw is not a valid CRAB project directory.
DEBUG 2016-07-01 03:21:43,522: 	 Executing command: 'status'
DEBUG 2016-07-01 03:21:43,522: 	 Found CRAB cache file /afs/cern.ch/user/j/junho/.crab3
ERROR 2016-07-01 03:21:43,522: 	 Error: crab_WJetsToLNu_TuneCUETP8M1_13TeV- is not a valid CRAB project directory.
ERROR 2016-07-01 03:21:43,522: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 254, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 749, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 563, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_WJetsToLNu_TuneCUETP8M1_13TeV- is not a valid CRAB project directory.
DEBUG 2016-08-15 06:08:24,314: 	 Executing command: 'report'
DEBUG 2016-08-15 06:08:24,315: 	 Found CRAB cache file /afs/cern.ch/user/j/junho/.crab3
DEBUG 2016-08-15 06:08:24,385: 	 Checking credentials
DEBUG 2016-08-15 06:08:24,385: 	 Proxy file /tmp/x509up_u81542 not found
DEBUG 2016-08-15 06:08:24,385: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-08-15 06:08:31,110: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 1
DEBUG 2016-08-15 06:08:31,514: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81542 -timeleft
 output : 
 error: Proxy not found: /tmp/x509up_u81542 (No such file or directory)

 retcode : 1
ERROR 2016-08-15 06:08:31,514: 	 Error while checking proxy timeleft for /tmp/x509up_u81542
DEBUG 2016-08-15 06:08:31,920: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u81542 voms-proxy-info -fqan
 output : 
 error: Proxy not found: /tmp/x509up_u81542 (No such file or directory)

 retcode : 1
ERROR 2016-08-15 06:08:31,921: 	 Problems creating proxy.
ERROR 2016-08-15 06:08:31,921: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/report.py", line 24, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2016-08-15 06:08:39,411: 	 Executing command: 'report'
DEBUG 2016-08-15 06:08:39,411: 	 Found CRAB cache file /afs/cern.ch/user/j/junho/.crab3
DEBUG 2016-08-15 06:08:39,417: 	 Checking credentials
DEBUG 2016-08-15 06:08:39,417: 	 Proxy file /tmp/x509up_u81542 not found
DEBUG 2016-08-15 06:08:39,417: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-08-15 06:08:44,231: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 1
DEBUG 2016-08-15 06:08:44,637: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81542 -timeleft
 output : 
 error: Proxy not found: /tmp/x509up_u81542 (No such file or directory)

 retcode : 1
ERROR 2016-08-15 06:08:44,638: 	 Error while checking proxy timeleft for /tmp/x509up_u81542
DEBUG 2016-08-15 06:08:45,042: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u81542 voms-proxy-info -fqan
 output : 
 error: Proxy not found: /tmp/x509up_u81542 (No such file or directory)

 retcode : 1
ERROR 2016-08-15 06:08:45,042: 	 Problems creating proxy.
ERROR 2016-08-15 06:08:45,043: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/report.py", line 24, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2016-08-15 06:08:55,706: 	 Executing command: 'report'
DEBUG 2016-08-15 06:08:55,706: 	 Found CRAB cache file /afs/cern.ch/user/j/junho/.crab3
DEBUG 2016-08-15 06:08:55,712: 	 Checking credentials
DEBUG 2016-08-15 06:08:55,712: 	 Proxy file /tmp/x509up_u81542 not found
DEBUG 2016-08-15 06:08:55,712: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-08-15 06:09:02,231: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 1
DEBUG 2016-08-15 06:09:02,635: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81542 -timeleft
 output : 
 error: Proxy not found: /tmp/x509up_u81542 (No such file or directory)

 retcode : 1
ERROR 2016-08-15 06:09:02,635: 	 Error while checking proxy timeleft for /tmp/x509up_u81542
DEBUG 2016-08-15 06:09:03,041: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u81542 voms-proxy-info -fqan
 output : 
 error: Proxy not found: /tmp/x509up_u81542 (No such file or directory)

 retcode : 1
ERROR 2016-08-15 06:09:03,041: 	 Problems creating proxy.
ERROR 2016-08-15 06:09:03,041: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/report.py", line 24, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2016-08-15 06:09:18,150: 	 Executing command: 'report'
DEBUG 2016-08-15 06:09:18,150: 	 Found CRAB cache file /afs/cern.ch/user/j/junho/.crab3
DEBUG 2016-08-15 06:09:18,156: 	 Checking credentials
DEBUG 2016-08-15 06:09:18,156: 	 Proxy file /tmp/x509up_u81542 not found
DEBUG 2016-08-15 06:09:18,156: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-08-15 06:09:23,376: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 1
DEBUG 2016-08-15 06:09:23,682: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81542 -timeleft
 output : 
 error: Proxy not found: /tmp/x509up_u81542 (No such file or directory)

 retcode : 1
ERROR 2016-08-15 06:09:23,682: 	 Error while checking proxy timeleft for /tmp/x509up_u81542
DEBUG 2016-08-15 06:09:23,986: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u81542 voms-proxy-info -fqan
 output : 
 error: Proxy not found: /tmp/x509up_u81542 (No such file or directory)

 retcode : 1
ERROR 2016-08-15 06:09:23,986: 	 Problems creating proxy.
ERROR 2016-08-15 06:09:23,986: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/report.py", line 24, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2016-08-15 11:24:15,157: 	 Executing command: 'report'
DEBUG 2016-08-15 11:24:15,157: 	 Found CRAB cache file /afs/cern.ch/user/j/junho/.crab3
DEBUG 2016-08-15 11:24:15,164: 	 Checking credentials
DEBUG 2016-08-15 11:24:15,164: 	 Proxy file /tmp/x509up_u81542 not found
DEBUG 2016-08-15 11:24:15,164: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-08-15 11:24:19,977: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 1
DEBUG 2016-08-15 11:24:20,384: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81542 -timeleft
 output : 
 error: Proxy not found: /tmp/x509up_u81542 (No such file or directory)

 retcode : 1
ERROR 2016-08-15 11:24:20,384: 	 Error while checking proxy timeleft for /tmp/x509up_u81542
DEBUG 2016-08-15 11:24:20,688: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u81542 voms-proxy-info -fqan
 output : 
 error: Proxy not found: /tmp/x509up_u81542 (No such file or directory)

 retcode : 1
ERROR 2016-08-15 11:24:20,688: 	 Problems creating proxy.
ERROR 2016-08-15 11:24:20,688: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/report.py", line 24, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2016-08-16 09:02:56,727: 	 Executing command: 'submit'
DEBUG 2016-08-16 09:02:56,728: 	 Found CRAB cache file /afs/cern.ch/user/j/junho/.crab3
DEBUG 2016-08-16 09:02:56,813: 	 Checking credentials
DEBUG 2016-08-16 09:02:56,814: 	 Found proxy file /tmp/x509up_u81542
DEBUG 2016-08-16 09:02:56,814: 	 Getting proxy life time left
DEBUG 2016-08-16 09:02:57,321: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81542 -timeleft
 output : 604595

 error: 
 retcode : 0
DEBUG 2016-08-16 09:02:57,826: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81542 -actimeleft
 output : 604594

 error: 
 retcode : 0
DEBUG 2016-08-16 09:02:57,827: 	 Proxy valid for 167:56:35 hours
INFO 2016-08-16 09:02:57,827: 	 Will use CRAB configuration file TTGJets_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8-crab.py
DEBUG 2016-08-16 09:02:57,827: 	 Loading CRAB configuration file.
DEBUG 2016-08-16 09:02:57,832: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-08-16 09:02:57,833: 	 Working area '/afs/cern.ch/work/j/junho/private/WA2Jets/WA_2Jets_crab/WA_2016/CMSSW_8_0_11/src/VAJets/PKUTreeMaker/test/crab_TTGJets_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8' already exists 
Please change the requestName in the config file
ERROR 2016-08-16 09:02:57,833: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/j/junho/private/WA2Jets/WA_2Jets_crab/WA_2016/CMSSW_8_0_11/src/VAJets/PKUTreeMaker/test/crab_TTGJets_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8' already exists 
Please change the requestName in the config file
DEBUG 2016-08-16 09:13:08,183: 	 Executing command: 'submit'
DEBUG 2016-08-16 09:13:08,183: 	 Found CRAB cache file /afs/cern.ch/user/j/junho/.crab3
DEBUG 2016-08-16 09:13:08,191: 	 Checking credentials
DEBUG 2016-08-16 09:13:08,191: 	 Found proxy file /tmp/x509up_u81542
DEBUG 2016-08-16 09:13:08,191: 	 Getting proxy life time left
DEBUG 2016-08-16 09:13:08,695: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81542 -timeleft
 output : 603984

 error: 
 retcode : 0
DEBUG 2016-08-16 09:13:09,200: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u81542 -actimeleft
 output : 603982

 error: 
 retcode : 0
DEBUG 2016-08-16 09:13:09,200: 	 Proxy valid for 167:46:24 hours
INFO 2016-08-16 09:13:09,200: 	 Will use CRAB configuration file WGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-crab.py
DEBUG 2016-08-16 09:13:09,200: 	 Loading CRAB configuration file.
DEBUG 2016-08-16 09:13:09,201: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-08-16 09:13:09,202: 	 Working area '/afs/cern.ch/work/j/junho/private/WA2Jets/WA_2Jets_crab/WA_2016/CMSSW_8_0_11/src/VAJets/PKUTreeMaker/test/crab_WGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8' already exists 
Please change the requestName in the config file
ERROR 2016-08-16 09:13:09,202: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/j/junho/private/WA2Jets/WA_2Jets_crab/WA_2016/CMSSW_8_0_11/src/VAJets/PKUTreeMaker/test/crab_WGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8' already exists 
Please change the requestName in the config file
DEBUG 2016-08-16 09:30:07,109: 	 Executing command: 'status'
DEBUG 2016-08-16 09:30:07,109: 	 Found CRAB cache file /afs/cern.ch/user/j/junho/.crab3
ERROR 2016-08-16 09:30:07,110: 	 Error: TTGJets_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8-crab.py is not a valid CRAB project directory.
ERROR 2016-08-16 09:30:07,110: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 257, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 749, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 566, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: TTGJets_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8-crab.py is not a valid CRAB project directory.
